version: '2'
services:
 app:
  image: thisisqasim/tastyigniter
#  build: .
  container_name: ordering_webapp
  ports:
  - "8001:80"
  environment:
  - MYSQL_HOSTNAME=
  - MYSQL_DATABASE=orderingdb
  - MYSQL_USER=orderingdbuser
  - MYSQL_PASSWORD=
  restart: always
 db:
  image: mariadb
  container_name: ordering_db
  volumes:
  - db_data:/var/lib/mysql
  environment:
  - MYSQL_DATABASE=orderingdb
  - MYSQL_USER=orderingdbuser
  - MYSQL_PASSWORD=
  restart: always
volumes:
  db_data:
    driver: local
uses: AlexxNB/caprover-action@v1
with:
  server: 'https://captain.platform.salemaziel.com'
  password: '${{ secrets.CAPROVER_PASSWORD }}'
  appname: 'ordering_webapp'